export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  brochure: string;
  category: string;
  tagline: string;
  desc: string;
  specs: string[];
  detailSpecs: ProductSpec[];
  img: string;
  thumbnail: string;
  tag: string;
  loadChart?: { extension: string; payload: number; counterweight: number }[];
}

export const products: Product[] = [
  {
    id: "SETU-20",
    slug: "setu-20",
    name: "SETU-20",
    brochure: "/brochures/catalog_setu.pdf",
    category: "Telescopic Crane",
    tagline: "Professional reach. Silent operation.",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["20' ft", "1 m/s Extension", "25 kg Payload"],
    detailSpecs: [
      { label: "Maximum Reach", value: "20 ft " },
      { label: "Extension Speed", value: "1 m/s" },
      { label: "Max Payload", value: "25 kg" },
      { label: "Arm Weight", value: "~100 kg" },
      { label: "Movement", value: "45 Degree Tilt & 360 Degree pan movement " },
      { label: "Motion", value: "Stabilized Telescopic arm motion" },
      { label: "Arm Speed", value: "Telescopic Arm speed 1 m/s per second " },
      { label: "Length", value: "Fully Extended length 32’ Feet   " },
      { label: "Head Type", value: "Hydraulic Fluid head" },
    ],
    thumbnail: "/product_setu_20.jpg",

    img: "/product_setu_20.jpg",
    tag: "[01]",
  },
  {
    id: "SETU-32",
    slug: "setu-32",
    name: "SETU-32",
    brochure: "/brochures/catalog_setu.pdf",
    category: "Telescopic Crane",
    tagline: "Professional reach. Silent operation.",
    desc: "32-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["32' ft", "1.5 m/s Extension", "40 kg Payload"],
    detailSpecs: [
      { label: "Maximum Reach", value: "32 ft " },
      { label: "Extension Speed", value: "1.5 m/s" },
      { label: "Max Payload", value: "40 kg" },
      { label: "Arm Weight", value: "~250 kg" },
      { label: "Movement", value: "45 Degree Tilt & 360 Degree pan movement " },
      { label: "Motion", value: "Stabilized Telescopic arm motion" },
      { label: "Arm Speed", value: "Telescopic Arm speed 1.5 m/s per second " },
      { label: "Length", value: "Fully Extended length 32’ Feet" },
      { label: "Head Type", value: "Hydraulic Fluid head" }
    ],
    thumbnail: "/product_setu_32.png",

    img: "/product_setu_32.png",
    tag: "[02]",
  },
  {
    id: "TRU-BASE GLIDER",
    slug: "trubase-glider",
    name: "TRU-BASE GLIDER",
    brochure: "/brochures/catalog_trubase.pdf",
    category: "Glider",
    tagline: "Speed meets stability.",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["360 degree Rotating seats", "Multi-Angle adjustment", "250 kg Payload"],
    detailSpecs: [
      { label: "Platform Type", value: "Specialized, Highly maneuverable camera platforms  " },
      { label: "Mounting", value: "Cheese Plate for Extensive mounting" },
      { label: "Max Payload", value: "250 kg" },
      { label: "Smoothness", value: "Smooth - Low angle shots" },
      { label: "Movement", value: "360 degree Rotating seats" },
      { label: "Motion", value: "Vertical and Horizontal height adjustable" },
      { label: "Angle Adjustment", value: "Multi-Angle adjustment" },
      { label: "Tires", value: "Adjustable pneumatic tires for All Terrains " },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_trubase.jpeg",

    img: "/product_trubase.jpeg",
    tag: "[03]",
  },

  {
    id: "AXIS GLIDER",
    slug: "axis-glider",
    name: "AXIS GLIDER",
    brochure: "/brochures/catalog_axisglider.pdf",
    category: "Glider",
    tagline: "Flawless Programmable Tracking",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Expandable Platform", "Multi-Angle adjustment", "40 to 100 kg Payload"],
    detailSpecs: [
      { label: "Control", value: "Touchscreen control" },
      { label: "Motion Control", value: "Motion Control and Programmable" },
      { label: "Max Payload", value: "100 kg" },
      { label: "Expandable Platform", value: "Upto : 9 Feet (3’Feet / 6’Feet / 9’Feet Track ) " },
      { label: "Payload Capacity", value: "Payload Capacity  Min: 40 Kg Max: 100 Kg" },
      { label: "Adjustment", value: "Vertical and Horizontal height adjustable" },
      // { label: "Angle Adjustment", value: "Multi-Angle adjustment" },
      { label: "Tires", value: "Fully Battery opreated. (2hr)" },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_axis.jpeg",

    img: "/product_axis.jpeg",
    tag: "[04]",
  },
  {
    id: "DUAL AXIS GLIDER 15",
    slug: "dual-axis-glider-15",
    name: "DUAL AXIS GLIDER (15)",
    brochure: "/brochures/catalog_dualaxis.pdf",
    category: "Glider",
    tagline: "Flawless Tracking",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Dual-Axis Working", "Multi Function Slider", "Smooth and Silent Movement"],
    detailSpecs: [
      { label: "Payload", value: "15Kg" },
      { label: "Platform Size", value: "2 FT X 4 FT Working" },
      { label: "Motion Control", value: "Dual-Axis Working" },
      { label: "Function", value: "Multi Function Slider" },
      { label: "Weight", value: "Light Weight and Easy to Carry (20 KG)" },
      { label: "Movement", value: "Smooth and Silent Movement" },
      { label: "Kickstart", value: "Easy To Setup" },
      // { label: "Angle Adjustment", value: "Easy To Setup" },
      { label: "Material", value: "Made from Aerospace grade alluminum " },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_dual.jpeg",

    img: "/product_dual.jpeg",
    tag: "[05]",
  },
  {
    id: "DUAL AXIS GLIDER 25",
    slug: "dual-axis-glider-25",
    name: "DUAL AXIS GLIDER (25)",
    brochure: "/brochures/catalog_dualaxis.pdf",
    category: "Glider",
    tagline: "Flawless Tracking",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Dual-Axis Working", "Multi Function Slider", "Smooth and Silent Movement"],
    detailSpecs: [
      { label: "Payload", value: "25Kg" },
      { label: "Platform Size", value: "2 FT X 4 FT Working" },
      { label: "Motion Control", value: "Dual-Axis Working" },
      { label: "Function", value: "Multi Function Slider" },
      { label: "Weight", value: "Light Weight and Easy to Carry (20 KG)" },
      { label: "Movement", value: "Smooth and Silent Movement" },
      { label: "Kickstart", value: "Easy To Setup" },
      { label: "Material", value: "Made from Aerospace grade alluminum " },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_dual.jpeg",

    img: "/product_dual.jpeg",
    tag: "[06]",
  },
  {
    id: "DIRECTORS BAY",
    slug: "director-s-bay-3-ft",
    name: "DIRECTORS BAY 3'Ft",
    brochure: "/brochures/catalog_directorbay.pdf",
    category: "Cart",
    tagline: "Set Command Center",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Multi Function", "Rigging Adjustment", "Light Weight & Easy To Carry"],
    detailSpecs: [
      { label: "Dimensions", value: "Length X Width X Height 3’ft   X 2’ft  X 3’ft" },
      { label: "Function", value: "Multi Function" },
      { label: "Adjustment", value: "Rigging Adjustment" },
      { label: "Mobility", value: "Light Weight & Easy To Carry" },
      { label: "Wheels", value: "All Terrain Wheels" },
      { label: "Movement", value: "Foldable as Carrybag" },
      { label: "Payload", value: "125kg" },
      // { label: "Material", value: "" },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_director.jpeg",

    img: "/product_director.jpeg",
    tag: "[07]",
  },
  {
    id: "DIRECTORS BAY",
    slug: "director-s-bay-3-5-ft",
    name: "DIRECTORS BAY 3-5'Ft",
    brochure: "/brochures/catalog_directorbay.pdf",
    category: "Cart",
    tagline: "Set Command Center",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Multi Function", "Rigging Adjustment", "Light Weight & Easy To Carry"],
    detailSpecs: [
      { label: "Dimensions", value: "Length X Width X Height 3.5’ft   X 2’ft  X 3’ft" },
      { label: "Function", value: "Multi Function" },
      { label: "Adjustment", value: "Rigging Adjustment" },
      { label: "Mobility", value: "Light Weight & Easy To Carry" },
      { label: "Wheels", value: "All Terrain Wheels" },
      { label: "Movement", value: "Foldable as Carrybag" },
      { label: "Payload", value: "125kg" },
      // { label: "Material", value: "" },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_director.jpeg",

    img: "/product_director.jpeg",
    tag: "[08]",
  },
  {
    id: "DIRECTORS BAY",
    slug: "director-s-bay-4-5-ft",
    name: "DIRECTORS BAY 4.5'Ft",
    brochure: "/brochures/catalog_directorbay.pdf",
    category: "Cart",
    tagline: "Set Command Center",
    desc: "20-foot reach. Entry-level performance with professional-grade belt drive. Ideal for studio and mid-scale productions.",
    specs: ["Multi Function", "Rigging Adjustment", "Light Weight & Easy To Carry"],
    detailSpecs: [
      { label: "Dimensions", value: "Length X Width X Height 4.5’ft   X 2’ft  X 3’ft" },
      { label: "Function", value: "Multi Function" },
      { label: "Adjustment", value: "Rigging Adjustment" },
      { label: "Mobility", value: "Light Weight & Easy To Carry" },
      { label: "Wheels", value: "All Terrain Wheels" },
      { label: "Movement", value: "Foldable as Carrybag" },
      { label: "Payload", value: "125kg" },
      // { label: "Material", value: "" },
      // { label: "", value: "Cost Effective" },      
    ],
    thumbnail: "/product_director.jpeg",

    img: "/product_director.jpeg",
    tag: "[09]",
  },
  // {
  //   id: "egc-40",
  //   slug: "egc-40",
  //   name: "SETU-40",
  //   category: "Telescopic Crane — Flagship",
  //   tagline: "The benchmark. Built for India's biggest sets.",
  //   desc: "40-foot reach. The benchmark product. Closed-loop PID control, MEMS gyroscope leveling, sub-pixel stability at full extension.",
  //   specs: ["40 ft / 12.2 m", "2.5 m/s Extension", "75 kg Payload"],
  //   detailSpecs: [
  //     { label: "Maximum Reach", value: "40 ft / 12.2 m" },
  //     { label: "Extension Speed", value: "2.5 m/s" },
  //     { label: "Max Payload (Over-slung)", value: "85 kg @ 10 ft / 60 kg @ 40 ft" },
  //     { label: "Max Payload (Under-slung)", value: "75 kg" },
  //     { label: "Arm Weight", value: "850 kg" },
  //     { label: "Lens Height (Max)", value: "25 ft (Over-slung)" },
  //     { label: "Drive System", value: "Steel-core Kevlar Timing Belt" },
  //     { label: "Leveling", value: "Fly-by-Wire — MEMS Gyro + Direct-Drive Servo" },
  //     { label: "Control", value: "Closed-loop PID" },
  //     { label: "Noise Floor", value: "< 20 dB at full speed" },
  //     { label: "Alloy", value: "7075-T6 Aerospace Aluminum" },
  //     { label: "Base Compatibility", value: "Mobile Base Pro / Chapman Hustler" },
  //     { label: "Travel", value: "Air-Suspension Truck Delivery" },
  //     { label: "SLA Response", value: "6-Hour Replacement (Mumbai / Hyderabad)" },
  //   ],
  //   img: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&h=900&q=80",
  //   tag: "[02]",
  //   loadChart: [
  //     { extension: "10 ft", payload: 85, counterweight: 200 },
  //     { extension: "20 ft", payload: 80, counterweight: 350 },
  //     { extension: "30 ft", payload: 70, counterweight: 500 },
  //     { extension: "40 ft (Max)", payload: 60, counterweight: 750 },
  //   ],
  // },
  // {
  //   id: "egc-60",
  //   slug: "egc-60",
  //   name: "SETU-60",
  //   category: "Telescopic Crane — Long Arm",
  //   tagline: "Epic reach. Zero compromise.",
  //   desc: "60-foot reach. Maximum reach for epic action sequences, stadium aerials, and large-scale Bollywood set pieces.",
  //   specs: ["60 ft / 18.3 m", "2.5 m/s Extension", "60 kg Payload"],
  //   detailSpecs: [
  //     { label: "Maximum Reach", value: "60 ft / 18.3 m" },
  //     { label: "Extension Speed", value: "2.5 m/s" },
  //     { label: "Max Payload", value: "60 kg @ full extension" },
  //     { label: "Arm Weight", value: "1,150 kg" },
  //     { label: "Lens Height (Max)", value: "38 ft (Over-slung)" },
  //     { label: "Drive System", value: "Dual Steel-core Kevlar Belt" },
  //     { label: "Leveling", value: "Fly-by-Wire — MEMS Gyro + Direct-Drive Servo" },
  //     { label: "Control", value: "Closed-loop PID, triple-redundant" },
  //     { label: "Noise Floor", value: "< 20 dB at full speed" },
  //     { label: "Alloy", value: "7075-T6 Aerospace Aluminum" },
  //     { label: "Fulcrum", value: "Boron Steel — Laser-Cut" },
  //     { label: "Base Compatibility", value: "Mobile Base Pro (Mandatory)" },
  //     { label: "Travel", value: "Dedicated Air-Suspension Delivery" },
  //     { label: "SLA Response", value: "6-Hour On-Site Engineer (Mumbai / Hyderabad)" },
  //   ],
  //   img: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&h=900&q=80",
  //   tag: "[03]",
  //   loadChart: [
  //     { extension: "10 ft", payload: 100, counterweight: 250 },
  //     { extension: "20 ft", payload: 85, counterweight: 450 },
  //     { extension: "40 ft", payload: 75, counterweight: 700 },
  //     { extension: "60 ft (Max)", payload: 60, counterweight: 1100 },
  //   ],
  // },
  // {
  //   id: "mobile-base-pro",
  //   slug: "mobile-base-pro",
  //   name: "Mobile Base Pro",
  //   category: "Platform Base",
  //   tagline: "Three steering modes. Zero compromise.",
  //   desc: "Three-mode steering: Conventional, Crab, and Round. 48V electric column elevation. Designed for the Chapman Hustler class of performance.",
  //   specs: ["Crab / Round / Conv.", "48V Electric Elevation", "300 kg Capacity"],
  //   detailSpecs: [
  //     { label: "Steering Modes", value: "Conventional, Crab, Round (360°)" },
  //     { label: "Elevation Drive", value: "48V Electric Column" },
  //     { label: "Load Capacity", value: "300 kg" },
  //     { label: "Wheel Locks", value: "Individual pneumatic per axle" },
  //     { label: "Chassis", value: "Boron Steel — CNC Laser-Cut" },
  //     { label: "Tread Width", value: "Adjustable 1.2 m – 2.4 m" },
  //     { label: "Crane Compatibility", value: "RKC-20 / RKC-40 / RKC-60" },
  //     { label: "Surface", value: "Film City Stage / Rajasthan Terrain Tested" },
  //   ],
  //   img: "https://images.pexels.com/photos/1117132/pexels-photo-1117132.jpeg?auto=compress&cs=tinysrgb&w=1200&h=900&fit=crop",
  //   tag: "[04]",
  // },
  // {
  //   id: "dit-cart",
  //   slug: "dit-cart",
  //   name: "DIT Cart Pro",
  //   category: "Production Cart",
  //   tagline: "From set to flight case. Under two minutes.",
  //   desc: "CNC-machined aluminum frame with 19-inch rack rails. Collapses to 7-inch flight case in under two minutes, without tools.",
  //   specs: ['19" Rack Integration', "Tool-less Collapse", "CNC Aluminum"],
  //   detailSpecs: [
  //     { label: "Frame Material", value: "CNC-Machined 6061-T6 Aluminum" },
  //     { label: "Rack Rails", value: '19" Standard — Full Height' },
  //     { label: "Collapse Time", value: "< 2 minutes, tool-less" },
  //     { label: "Collapsed Profile", value: "7 inches (ATA-flight-ready)" },
  //     { label: "Monitors", value: "Up to 2× 24-inch display mounts" },
  //     { label: "Power", value: "12-outlet PDU, 20A breaker" },
  //     { label: "Wheels", value: "4× Lockable swivel casters" },
  //     { label: "Weight", value: "38 kg (assembled)" },
  //   ],
  //   img: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=1200&h=900&q=80",
  //   tag: "[05]",
  // },
  // {
  //   id: "camera-cart",
  //   slug: "camera-cart",
  //   name: "Camera Cart HD",
  //   category: "Production Cart",
  //   tagline: "Built for the pace of an Indian film set.",
  //   desc: "Heavy-duty camera and lens cart. Aerospace-grade quick-release pins. Built for the pace and chaos of a working Indian film set.",
  //   specs: ["120 kg Rated", "Aerospace Pins", "Modular Configuration"],
  //   detailSpecs: [
  //     { label: "Rated Load", value: "120 kg" },
  //     { label: "Quick-Release System", value: "Aerospace-grade locking pins" },
  //     { label: "Tray System", value: "Modular — 4× configurable trays" },
  //     { label: "Lens Storage", value: "Foam-lined, 12-lens capacity" },
  //     { label: "Handle Height", value: "Adjustable 85 – 115 cm" },
  //     { label: "Wheels", value: "200mm pneumatic — cobblestone rated" },
  //     { label: "Frame", value: "4130 Chromoly Steel" },
  //     { label: "Surface Treatment", value: "Powder coated — set environment rated" },
  //   ],
  //   img: "https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?auto=format&fit=crop&w=1200&h=900&q=80",
  //   tag: "[06]",
  // },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getAdjacentProducts(slug: string): { prev: Product | null; next: Product | null } {
  const idx = products.findIndex((p) => p.slug === slug);
  return {
    prev: idx > 0 ? products[idx - 1] : null,
    next: idx < products.length - 1 ? products[idx + 1] : null,
  };
}
